import type { Element, Root } from "hast";
import { Check, Clipboard } from "lucide-react";
import type { ComponentPropsWithoutRef } from "react";
import { memo, useContext, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import ReactMarkdown from "react-markdown";
import rehypeSanitize from "rehype-sanitize";
import remarkBreaks from "remark-breaks";
import remarkGfm from "remark-gfm";
import { isLocalArtifactLink } from "../../../protocol/artifacts.ts";
import { ArtifactContext } from "../features/artifacts/context.ts";
import { copyText } from "../lib/clipboard.ts";
import type { RootContent } from "hast";

function labelTaskCheckboxes() {
  return (tree: Root) => {
    const text = (node: RootContent): string =>
      node.type === "text"
        ? node.value
        : node.type === "element" && !["ul", "ol"].includes(node.tagName)
          ? node.children.map(text).join("")
          : "";
    const walk = (node: Root | Element) => {
      if (
        node.type === "element" &&
        (node.tagName === "li" || node.tagName === "p")
      ) {
        const label = text(node).trim();
        for (const child of node.children) {
          if (
            child.type === "element" &&
            child.tagName === "input" &&
            child.properties.type === "checkbox" &&
            label
          )
            child.properties.ariaLabel = label;
        }
      }
      for (const child of node.children)
        if (child.type === "element") walk(child);
    };
    walk(tree);
  };
}

declare module "hast" {
  interface ElementData {
    openpiWindowsPath?: string;
  }
}

function preserveWindowsLinks() {
  return (tree: Root) => {
    const walk = (node: Root | Element) => {
      if (node.type === "element") {
        const key =
          node.tagName === "a"
            ? "href"
            : node.tagName === "img"
              ? "src"
              : undefined;
        const raw = key ? node.properties[key] : undefined;
        // Markdown's URI normalization percent-encodes Windows backslashes.
        const value =
          typeof raw === "string" ? raw.replace(/%5c/giu, "\\") : raw;
        if (
          key &&
          typeof value === "string" &&
          /^[a-z]:[\\/]/iu.test(value) &&
          !/[\x00-\x1f\x7f]/u.test(value)
        ) {
          node.data = { ...node.data, openpiWindowsPath: value };
          node.properties[key] = "./";
        }
      }
      for (const child of node.children)
        if (child.type === "element") walk(child);
    };
    walk(tree);
  };
}

// Node data is generated by our plugin and retained by sanitize; it is not a URL namespace.
function windowsLink(node?: Element) {
  const value = node?.data?.openpiWindowsPath;
  return typeof value === "string" ? value : undefined;
}

function safeUrl(value: string) {
  if (!value.trim()) return "";
  try {
    const url = new URL(value, document.baseURI);
    return ["http:", "https:", "mailto:", "tel:"].includes(url.protocol)
      ? url.href
      : "";
  } catch {
    return "";
  }
}

function CodeBlock({
  children,
  node: _node,
  ...props
}: ComponentPropsWithoutRef<"pre"> & { node?: Element }) {
  const { t } = useTranslation();
  const [copyStatus, setCopyStatus] = useState<
    "idle" | "copying" | "copied" | "failed"
  >("idle");
  const copyGeneration = useRef(0);
  const copyTimer = useRef<number | undefined>(undefined);
  const code = useRef<HTMLPreElement>(null);
  useEffect(
    () => () => {
      copyGeneration.current += 1;
      window.clearTimeout(copyTimer.current);
    },
    [],
  );
  const copied = copyStatus === "copied";
  return (
    <div className="markdown-code-block">
      <div className="markdown-code-toolbar">
        {copyStatus === "failed" && (
          <span role="status">{t("copyCodeFailed")}</span>
        )}
        <button
          type="button"
          aria-label={copied ? t("copiedCode") : t("copyCode")}
          title={copied ? t("copiedCode") : t("copyCode")}
          disabled={copyStatus === "copying"}
          onClick={() => {
            const generation = ++copyGeneration.current;
            window.clearTimeout(copyTimer.current);
            setCopyStatus("copying");
            void copyText(code.current?.textContent ?? "").then((success) => {
              if (generation !== copyGeneration.current) return;
              setCopyStatus(success ? "copied" : "failed");
              if (success)
                copyTimer.current = window.setTimeout(
                  () => setCopyStatus("idle"),
                  1_200,
                );
            });
          }}
        >
          {copied ? (
            <Check aria-hidden="true" />
          ) : (
            <Clipboard aria-hidden="true" />
          )}
        </button>
      </div>
      <section
        className="markdown-code-scroll"
        aria-label={t("codeBlock")}
        // biome-ignore lint/a11y/noNoninteractiveTabindex: Long code needs a keyboard-focusable horizontal scroll region.
        tabIndex={0}
        onKeyDown={(event) => {
          if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
          const target = event.currentTarget;
          if (target.scrollWidth <= target.clientWidth) return;
          event.preventDefault();
          target.scrollLeft += event.key === "ArrowRight" ? 40 : -40;
        }}
      >
        <pre ref={code} {...props}>
          {children}
        </pre>
      </section>
    </div>
  );
}

export const Markdown = memo(function Markdown({
  children,
}: {
  children: string;
}) {
  const artifacts = useContext(ArtifactContext);
  return (
    <div className="markdown">
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkBreaks]}
        rehypePlugins={[
          preserveWindowsLinks,
          rehypeSanitize,
          labelTaskCheckboxes,
        ]}
        urlTransform={(value) =>
          isLocalArtifactLink(value) ? value : safeUrl(value)
        }
        components={{
          pre: CodeBlock,
          table({ children, ...props }) {
            return (
              <section
                className="markdown-table-scroll"
                aria-label="Table"
                // biome-ignore lint/a11y/noNoninteractiveTabindex: Wide tables need a keyboard-focusable horizontal scroll region.
                tabIndex={0}
              >
                <table {...props}>{children}</table>
              </section>
            );
          },
          a({ href, node, children: label, ...props }) {
            href = windowsLink(node) ?? href;
            if (isLocalArtifactLink(href ?? ""))
              return artifacts ? (
                <button
                  type="button"
                  className="artifact-link"
                  title={`Open read-only file: ${href}`}
                  onClick={() => artifacts.open(href ?? "", artifacts.parent)}
                >
                  {label}
                  <small className="artifact-link-path" aria-hidden="true">
                    {" "}
                    ({href})
                  </small>
                </button>
              ) : (
                <span title="Open this file from its Session">{label}</span>
              );
            const safeHref = safeUrl(href ?? "");
            return safeHref ? (
              <a {...props} href={safeHref} target="_blank" rel="noreferrer">
                {label}
              </a>
            ) : (
              label
            );
          },
          img({ src, node, alt, title }) {
            src = windowsLink(node) ?? src;
            if (isLocalArtifactLink(src ?? ""))
              return artifacts ? (
                <button
                  type="button"
                  className="artifact-link"
                  title={`Open read-only file: ${src}`}
                  onClick={() => artifacts.open(src ?? "", artifacts.parent)}
                >
                  [image: {alt || "image"}]
                  <small className="artifact-link-path" aria-hidden="true">
                    {" "}
                    ({src})
                  </small>
                </button>
              ) : (
                <span>[image: {alt || "image"}]</span>
              );
            const safeHref = safeUrl(src ?? "");
            const label = alt || "image";
            return safeHref ? (
              <a href={safeHref} title={title} target="_blank" rel="noreferrer">
                [image: {label}]
              </a>
            ) : (
              <span>{label}</span>
            );
          },
        }}
      >
        {children}
      </ReactMarkdown>
    </div>
  );
});
